My_Blog/My_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app_login.urls')),
    path('blogs/', include('app_blog.urls')),
    path('', views.Index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog/app_blog/urls.py
from django.urls import path
from . import views 

app_name = 'app_blog'

urlpatterns = [
    path('',views.blog_list.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/', views.unlike, name='unliked'),
    path('my_blog/', views.myBlog.as_view(), name='my_blog'),
    path('update_blog/<pk>/', views.updateBlog.as_view(), name='update_blog'),
    path('delete_blog/<pk>/',views.deleteBlog.as_view(), name='delete_blog')
]

My_Blog/app_blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='post_author')
    blog_title = models.CharField(max_length=264, verbose_name="Add a Title")
    slug = models.SlugField(max_length=264, unique=True)
    blog_content = models.TextField(verbose_name="what is on your mind?")
    blog_image = models.ImageField(upload_to='blog_images', verbose_name="Blog Image")
    publish_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    
    """
    class Meta:
        ordering = ['-publish_date'] #another way of oredring by objects instead of queryset
    """
    
    def __str__(self):
        return self.blog_title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comments')
    user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_comments')
    comment = models.TextField(verbose_name="Type Your Comment:")
    comment_date = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-comment_date']
    
    def __str__(self):
        return self.comment
class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='liked_blog')
    user = models.ForeignKey(User, on_delete=models.CASCADE,related_name='liked_user')
    
    def __str__(self):
        return self.user + 'Likes' + self.blog
    
     

My_Blog/app_blog/forms.py
from django import forms
from .models import  Blog,Comment,Like

class commentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment', )

My_Blog/My_Blog/views.py
from django.http import HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse

def Index(request):
    return HttpResponseRedirect(reverse('app_blog:blog_list'))

My_Blog/app_blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView,ListView,UpdateView,DetailView,DeleteView,View,TemplateView
from .models import Comment, Like, Blog
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
from .forms import commentForm

# Create your views here.
class blog_list(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'app_blog/blog_list.html'
    queryset = Blog.objects.order_by('-publish_date')

class myBlog(LoginRequiredMixin, TemplateView):
    model = Blog
    template_name = 'app_blog/my_blog.html'
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['title'] = 'My Blog'
        return context
    
    

class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'app_blog/create_blog.html'
    
    def get_context_data(self, **kwargs):
        context= super().get_context_data(**kwargs)
        context['title'] = 'Write a Blog'
        return context
    
    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        title = blog_obj.blog_title
        blog_obj.slug = title.replace(" ","-")+ "-" + str(uuid.uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('index'))
    
@login_required
def blog_details(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = commentForm()
    already_liked = Like.objects.filter(blog=blog, user= request.user)
    
    if already_liked:
        liked = True
    else:
        liked = False
        
    if request.method == 'POST':
        comment_form = commentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':slug}))

    diction = {'blog':blog, 'comment_form':comment_form, 'liked': liked}
    return render(request, 'app_blog/blog_details.html', context=diction)

@login_required
def liked(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if not already_liked:
        like_post = Like(blog=blog, user=user)
        like_post.save()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':blog.slug}))

@login_required
def unlike(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('app_blog:blog_details', kwargs={'slug':blog.slug}))

class updateBlog(LoginRequiredMixin,UpdateView):
    model = Blog
    fields = ('blog_title', 'blog_content', 'blog_image')
    template_name = 'app_blog/edit_blog.html'
    
    def get_success_url(self, **kwargs):
        return reverse_lazy('app_blog:blog_details', kwargs={'slug':self.object.slug})

class deleteBlog(LoginRequiredMixin, DeleteView):
    model = Blog
    template_name = 'app_blog/delete_blog.html'
    success_url = reverse_lazy('app_blog:my_blog')

My_Blog/templates/app_blog/blog_details.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titleblock %} Read Blog {% endblock titleblock %}

{% block bodyblock %}
    <div class="row">
        <div class="col-sm-5">
            <h3 style="color:#0f6191">{{blog.blog_title}}</h3>
            <h6 style="color:#02bf0b">@{{blog.author}}</h6><br>
            <i>published on {{blog.publish_date}}</i><br>
            <i>updated on {{blog.update_date}}</i>
            <h6 style="color:#0f6191">{{blog.liked_blog.count}} Likes || {{blog.blog_comments.count}} Comments</h6>
            
        </div>
        <div class="col-sm-5">
        <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">
        </div>
        <div class='col-sm-1'></div>
        <div class="col-sm-10">
        <br><p>{{blog.blog_content|linebreaks}}</p>
        </div>
        <div class='col-sm-1'></div>
        
    </div>
    <hr>
    {% if liked %}
    <a href="{% url 'app_blog:unliked' pk=blog.pk %}">
        <h4 style="color:#0f6191"><i class="fa fa-thumbs-o-down fa" aria-hidden="true"> Unlike</i></h4>
    </a>
    {% else %}
    <a href="{% url 'app_blog:liked' pk=blog.pk %}">
        <h4 style="color:#0f6191"><i class="fa fa-thumbs-o-up fa" aria-hidden="true"> Like</i></h4>
    </a>
    {% endif %}
    <br>
    <br>
    <div class="row">
        
        <div class="col-sm-7">
        <hr>
        <hr>
            <h3 style="color:#946300">Comments</h3>
            {% for comment in blog.blog_comments.all %}
            <a href="#">@{{comment.user}}</a> <i>__{{comment.comment_date}}</i><br>
            <p>{{comment.comment}}</p>
            {% endfor %}
            <br>
            
        </div>
        
        <div class="col-sm-5">
            <hr>
            <hr>
            <form method="POST">
                {{comment_form|crispy}}
                {% csrf_token %}
                <button class="btn btn-primary btn-sm">comment</button>
                <br><br>
            </form>

        </div>
    </div>
    <hr>

{% endblock bodyblock %}

My_Blog/templates/app_blog/blog_list.html
{% extends 'base.html' %}
{% load custom_filters %}
{% block titleblock %} Home {% endblock titleblock %}


{% block bodyblock %}
    {% for blog in blogs %}
        <div class="row">
            <div class="col-sm-4">
                <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%">    
            </div>
            <div class="col-sm-8">
                <h4>{{blog.blog_title}}</h4>
                <b>@{{blog.author}}</b> <i>_{{blog.publish_date}}</i>
                <h6 style="color:#0f6191">{{blog.liked_blog.count}} Likes || {{blog.blog_comments.count}} Comments</h6>
                <hr>
                <p>  {{blog.blog_content|range_filter|linebreaks}}<a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read All</a></p>
            </div>
        </div>
        <br><hr>
    {% endfor %}
    
{% endblock bodyblock %}

My_Blog/templates/app_blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titleblock %} {{title}} {% endblock titleblock %}

{% block bodyblock %}
    <h3>Write a new Blog here...</h3>
    <form method='POST' enctype='multipart/form-data'>
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-success btn-md">Post</button>
    </form>
{% endblock bodyblock %}

My_Blog/templates/app_blog/delete_blog.html
{% extends 'base.html' %}

{% block titleblock %} {% endblock  %}

{% block bodyblock %}
    <div class="alert alert-warning">
        <h5>Delete this Blog titled <strong>"{{ blog.blog_title}}"</stong>?</h5>
    </div>
    <center>
    <form method='POST'>
    {% csrf_token %}
    <input class='btn btn-danger btn-md' type="submit" name='delete' value="delete">
    <a href="{% url 'app_blog:my_blog'%}" class="btn btn-info btn-md">Return</a>
    </form>
    </center>

{% endblock bodyblock %}

My_Blog/templates/app_blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titleblock %} <h3>Edit This Blog</h3> {% endblock titleblock %}

{% block bodyblock %}

{% if blog.author == user %}
    <form method='POST'>
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class= "btn btn-info btn-sm">update</button>
    </form>
{% else %}
    <p>You are not allowed to view this page. 404</p>
{% endif %}
{% endblock bodyblock %}

My_Blog/templates/app_blog/my_blog.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block titleblock %} {{title}} {% endblock titleblock %}

{% block bodyblock %}
    {% for blog in user.post_author.all %}
    <div class="row">
            <div class="col-sm-4">
                <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%" height="285px">    
            </div>
            <div class="col-sm-8">
                <h4>{{blog.blog_title}}</h4>
                <i>{{blog.publish_date}}</i>
                <h6 style="color:#0f6191">{{blog.liked_blog.count}} Likes || {{blog.blog_comments.count}} Comments</h6>
                <hr>
                <p>  {{blog.blog_content|range_filter|linebreaks}}<a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read All</a></p>
                <a href="{% url 'app_blog:update_blog' pk=blog.pk%}" class="btn btn-info btn-sm">Edit Blog</a>
                <a href="{% url 'app_blog:delete_blog' pk=blog.pk%}" class="btn btn-sm btn-warning">Delete</a>
                
            </div>
        </div>
        <br><hr>
    
    {% endfor %}
{% endblock bodyblock %}