My_Blog/My_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app_login.urls')),
    path('blogs/', include('app_blog.urls')),
    path('', views.Index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog/app_blog/urls.py
from django.urls import path
from . import views 

app_name = 'app_blog'

urlpatterns = [
    path('',views.blog_list.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/', views.unlike, name='unliked'),
    path('my_blog/', views.myBlog.as_view(), name='my_blog'),
    path('update_blog/<pk>/', views.updateBlog.as_view(), name='update_blog'),
    path('delete_blog/<pk>/',views.deleteBlog.as_view(), name='delete_blog')
]

My_Blog/app_login/urls.py
from django.urls import path
from . import views

app_name='app_login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/',views.log_in, name='login' ),
    path('logout/',views.log_out, name='logout' ),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.user_change, name='edit_profile'),
    path('password/', views.change_pass, name='change_pass'),
    path('add_pro_pic/', views.add_pro_pic, name='add_pro_pic'),
    path('change_pro_pic/', views.change_pro_pic, name='change_pro_pic'),
]

My_Blog/app_login/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    profile_pic = models.ImageField(upload_to='profile_pics')

My_Blog/app_login/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django import forms
from .models import UserProfile

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label="Email Address", required=True)
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name', 'password')

class ProfilePics(forms.ModelForm):
    profile_pic = forms.ImageField(label='Profile Picture')
    class Meta:
        model = UserProfile
        fields = ('profile_pic',)

My_Blog/app_login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import SignUpForm,UserProfileChange,ProfilePics


# Create your views here.
def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registered = True
    diction = {'form':form, 'registered':registered, 'title':'Signup - User'}
    return render(request, 'app_login/signup.html', context=diction)

def log_in(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return HttpResponseRedirect(reverse('app_login:profile'))
    diction={'form':form, 'title':'Login - User'}        
    return render(request,'app_login/login_page.html',context=diction)

@login_required
def log_out(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile(request):
    diction = {'title':'My Profile'}
    return render(request, 'app_login/profile.html', context=diction)
@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    diction = {'form':form}
    return render(request, 'app_login/change_profile.html', context=diction)

@login_required
def change_pass(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method=='POST':
        form = PasswordChangeForm(current_user,data=request.POST)
        if form.is_valid():
            form.save()
            form = PasswordChangeForm(current_user)
            changed = True
    diction = {'form':form, 'changed':changed}
    return render(request, 'app_login/change_pass.html', context=diction)

@login_required
def add_pro_pic(request):
    form = ProfilePics()
    if request.method == 'POST':
        form = ProfilePics(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request, 'app_login/add_pro_pic.html', context={'form':form})

@login_required
def change_pro_pic(request):
    form = ProfilePics(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePics(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    return render(request, 'app_login/change_pro_pic.html', context={'form':form})

My_Blog/templates/app_login/add_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titleblock %} Profile Picture{% endblock titleblock %}

{% block bodyblock %}
    <h3>Add a Profile Picture</h3>
    <form method='POST' enctype='multipart/form-data'>
        {{form|crispy}}
        {% csrf_token %}
        <button class='btn btn-success btn-sm' type='submit'>Set Image</button>
    </form>
{% endblock bodyblock %}

My_Blog/templates/app_login/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titleblock %} Change Password{% endblock titleblock %}
{% block bodyblock %}
{% if changed %}
    <div class="alert alert-success">
        Password Changed Successfully!
    </div>
{% else %}
    <form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button class="btn btn-warning btn-sm" type="submit">Change</button>
    </form>
{% endif %}
{% endblock bodyblock %}

My_Blog/templates/app_login/change_pro_pic.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titleblock %} Change Image{% endblock titleblock %}

{% block bodyblock %}
    <h3>Change Profile Picture</h3>
    
    <form method='POST' enctype='multipart/form-data'>
    <img src="/media/{{user.user_profile.profile_pic}}" class='rounded-circle' height='100px' width='110px'>
        {{form|crispy}}
        {% csrf_token %}
        <button class='btn btn-success btn-sm' type='submit'>Change Image</button>
    </form>
{% endblock bodyblock %}

My_Blog/templates/app_login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titleblock %} Edit Profile {% endblock titleblock %}

{% block bodyblock %}
<h3>Edit Profile</h3>
    <form method="POST">
        {{form|crispy}}
        {% csrf_token %}
        <button class="btn btn-warning btn-sm" type="submit">Update</button>
        
    </form>
{% endblock bodyblock %}

My_Blog/templates/app_login/login_page.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block titleblock %} {{title}} {% endblock titleblock %}

{% block bodyblock %}
    <h3>Login:</h3>
    <form method='POST'>
        {{form|crispy}}
        {% csrf_token %}
        <button type="submit" class="btn btn-primary btn-sm">Login</button>
    </form>
    <br>
    <p>Don't have any account yet? please<a href="{% url 'app_login:signup'%}"> SignUp</a></p>
{% endblock bodyblock %}

My_Blog/templates/app_login/profile.html
{% extends 'base.html' %}
{% load custom_filters %}

{% block titleblock %} {% endblock titleblock %}

{% block bodyblock %}
        <div class="row">
        <div class="col-sm-4">
        <h4>{{user.username}}'s Profile</h4><br>
        {% if user.user_profile%}
        <img src="/media/{{user.user_profile.profile_pic}}" class='rounded-circle' height='100px' width='110px'>
        <br><br>
        <a href="{% url 'app_login:change_pro_pic'%}" class='btn btn-info btn-sm'>Change Image</a>
        <br><br>
        {% else %}
        <img src="/media/profile_pics/demo.png" class='rounded-circle' height='150px' width='170px'><br><br>
        <a href="{% url 'app_login:add_pro_pic'%}" class='btn btn-info btn-sm'>Add Profile Pic</a>
        
        {% endif %}
        <p>Username: {{user.username}}</p>
        <p>Email: {{user.email}}</p>
        <p>Name: {{user.first_name}} {{user.last_name}}</p>
        
        <a href="{% url 'app_login:edit_profile'%}" class="btn btn-warning btn-sm">Update Profile</a>
        </div>
        </div>
        <br><br>
        <center><h4 style='color:blue'>Your Content</h4></center>
        <hr><hr>

        {% for blog in user.post_author.all %}
        <div class='row'>
        <div class="col-sm-2">
            <img src="/media/{{blog.blog_image}}" alt="{{blog.blog_title}}" title="{{blog.blog_title}}" width="100%" height="115px">    
        </div>
        <div class="col-sm-10">
            <h5>{{blog.blog_title}}</h5>
            <i>{{blog.publish_date}}</i>
            <h6 style="color:#0f6191">{{blog.liked_blog.count}} Likes || {{blog.blog_comments.count}} Comments</h6>
            <a href="{% url 'app_blog:update_blog' pk=blog.pk%}" class="btn btn-info btn-sm">Edit Blog</a>
            <a href="{% url 'app_blog:delete_blog' pk=blog.pk%}" class="btn btn-sm btn-danger">Delete</a>
            
        </div>
            <div class="row" style="padding-left:25px">
            <div class="col-sm-12">
            <p>  {{blog.blog_content|range_filter|linebreaks}}<a href="{% url 'app_blog:blog_details' slug=blog.slug %}">Read All</a></p>
            </div>
            </div>
        </div>
        <br><hr>
        {% endfor %}
        

{% endblock bodyblock %}

My_Blog/templates/app_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block titleblock %} {{title}} {% endblock titleblock %}

{% block bodyblock %}
    {% if registered %}
    <div class="alert alert-success">
    Account Has Created Successfully... <a href="{% url 'app_login:login'%}">Login here</a>
    </div>
    {% else %}
    <h3>Create New Account</h3>
    <br>
    <form method='POST'>
        {{form|crispy}}
        {% csrf_token %}
        <button type='submit' class="btn btn-success btn-sm">Create Account</button>
    </form>
    <br>
    <p>already have an account?... <a href="{% url 'app_login:login'%}">Login here</a></p>
    {% endif %}
{% endblock bodyblock %}