My_Blog/My_Blog/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views 
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('app_login.urls')),
    path('blogs/', include('app_blog.urls')),
    path('', views.Index, name='index'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_Blog/app_blog/urls.py
from django.urls import path
from . import views 

app_name = 'app_blog'

urlpatterns = [
    path('',views.blog_list.as_view(), name='blog_list'),
    path('write/', views.CreateBlog.as_view(), name='create_blog'),
    path('details/<slug>', views.blog_details, name='blog_details'),
    path('liked/<pk>/', views.liked, name='liked'),
    path('unliked/<pk>/', views.unlike, name='unliked'),
    path('my_blog/', views.myBlog.as_view(), name='my_blog'),
    path('update_blog/<pk>/', views.updateBlog.as_view(), name='update_blog'),
    path('delete_blog/<pk>/',views.deleteBlog.as_view(), name='delete_blog')
]

My_Blog/app_login/urls.py
from django.urls import path
from . import views

app_name='app_login'

urlpatterns = [
    path('signup/', views.sign_up, name='signup'),
    path('login/',views.log_in, name='login' ),
    path('logout/',views.log_out, name='logout' ),
    path('profile/', views.profile, name='profile'),
    path('edit_profile/', views.user_change, name='edit_profile'),
    path('password/', views.change_pass, name='change_pass'),
    path('add_pro_pic/', views.add_pro_pic, name='add_pro_pic'),
    path('change_pro_pic/', views.change_pro_pic, name='change_pro_pic'),
]

My_Blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
  <!-- jQuery library -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <!-- Popper JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <!-- Latest compiled JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
  <title>{% block title_block %} {{title}} {% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark" text-align="center">
        <ul class="navbar-nav">
            <li class= "nav-item active">
                <a class="nav-link" href="{% url 'index'%}"><img src="/media/logo.png" width="22px" height="20px" style="margin-bottom:10px"> Home</a>
                
            </li>
            
            {% if user.is_authenticated %}
            <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" id="navdrop" data-toggle="dropdown">@{{user.username}}</a>
            
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'app_blog:create_blog'%}">Write Blog</a>
                    <a class="dropdown-item" href="{% url 'app_blog:my_blog'%}">My Blog</a>
                    <a class="dropdown-item" href="{% url 'app_login:profile'%}">My Profile</a>
                    <br>
                    <a class="dropdown-item" href="{% url 'app_login:logout'%}">Logout</a>
                </div>
            </div>

            {% else %}
            <li class= "nav-item active">
                <a class="nav-link" href="{% url 'app_login:signup'%}">Sign Up</a>
            </li>
            
            <li class= "nav-item active">
                <a class="nav-link" href="{% url 'app_login:login'%}">Login</a>
            </li>
            {% endif %}
        </ul>

    </nav>
    <div class="container" style="padding-top:30px">
        {% block bodyblock %}
        {% endblock bodyblock %}
    </div>
</body>
</html>